# Generated by Django 5.1.1 on 2024-09-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='id',
        ),
        migrations.AddField(
            model_name='tarea',
            name='IDtarea',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
