# Generated by Django 5.1.2 on 2024-10-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insignias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='awarded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
