# Generated by Django 5.1.1 on 2024-09-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_us',
            field=models.CharField(choices=[('Jefe', 'Jefe'), ('Empleado', 'Empleado')], default='Empleado', max_length=10),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
